export {
  CnosSecurityError,
  createSecretVault,
  flattenObject,
  loadManifest,
  listSecretVaults,
  parseYaml,
  resolveManifestRoot,
  resolveConfigDocumentPath,
  resolveSecretPassphrase,
  resolveSecretStoreRoot,
  resolveSecretVaultFile,
  stringifyYaml,
  validateRuntime,
  ensureProjectionAllowed,
  writeLocalSecret,
  type SecretReference,
  type ValidationIssue,
  type ValidationSummary,
  type WorkspaceFile,
} from '@kitsy/cnos-core';
