import type { NormalizedManifest, SchemaRule } from '@kitsy/cnos-core';

export interface GeneratedCodegenContent {
  typesContent: string;
  runtimeContent: string;
  schemaEntryCount: number;
  hasSchema: boolean;
}

function toPascalCase(value: string): string {
  return value
    .split(/[^A-Za-z0-9]+/)
    .filter((segment) => segment.length > 0)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join('');
}

function mapSchemaType(rule: SchemaRule | undefined): string {
  switch (rule?.type) {
    case 'number':
      return 'number';
    case 'string':
      return 'string';
    case 'boolean':
      return 'boolean';
    case 'object':
      return 'Record<string, unknown>';
    case 'array':
      return 'unknown[]';
    default:
      return 'unknown';
  }
}

function isOptional(rule: SchemaRule | undefined): boolean {
  return !(rule?.required ?? false) && rule?.default === undefined;
}

function buildNamespaceInterfaces(schema: NormalizedManifest['schema']): string[] {
  const namespaceGroups = new Map<string, Array<{ key: string; rule: SchemaRule }>>();

  for (const [logicalKey, rule] of Object.entries(schema).sort(([left], [right]) => left.localeCompare(right))) {
    const separatorIndex = logicalKey.indexOf('.');

    if (separatorIndex <= 0 || separatorIndex >= logicalKey.length - 1) {
      continue;
    }

    const namespace = logicalKey.slice(0, separatorIndex);
    const path = logicalKey.slice(separatorIndex + 1);
    const existing = namespaceGroups.get(namespace) ?? [];
    existing.push({
      key: path,
      rule,
    });
    namespaceGroups.set(namespace, existing);
  }

  const orderedNamespaces = Array.from(namespaceGroups.keys()).sort((left, right) => {
    if (left === 'value') {
      return -1;
    }

    if (right === 'value') {
      return 1;
    }

    if (left === 'secret') {
      return -1;
    }

    if (right === 'secret') {
      return 1;
    }

    return left.localeCompare(right);
  });

  if (orderedNamespaces.length === 0) {
    return [
      'export interface CnosValueConfig {}',
      'export interface CnosSecretConfig {}',
      '',
      'export interface CnosConfig {',
      '  value: CnosValueConfig;',
      '  secret: CnosSecretConfig;',
      '}',
    ];
  }

  const blocks: string[] = [];

  for (const namespace of orderedNamespaces) {
    const entries = namespaceGroups.get(namespace) ?? [];
    const interfaceName =
      namespace === 'value'
        ? 'CnosValueConfig'
        : namespace === 'secret'
          ? 'CnosSecretConfig'
          : `Cnos${toPascalCase(namespace)}Config`;

    blocks.push(`export interface ${interfaceName} {`);

    for (const entry of entries) {
      const optional = isOptional(entry.rule) ? '?' : '';
      blocks.push(`  "${entry.key}"${optional}: ${mapSchemaType(entry.rule)};`);
    }

    blocks.push('}');
    blocks.push('');
  }

  const configEntries = orderedNamespaces.map((namespace) => {
    const interfaceName =
      namespace === 'value'
        ? 'CnosValueConfig'
        : namespace === 'secret'
          ? 'CnosSecretConfig'
          : `Cnos${toPascalCase(namespace)}Config`;

    return `  ${namespace}: ${interfaceName};`;
  });

  blocks.push('export interface CnosConfig {');
  blocks.push(...configEntries);
  blocks.push('}');

  if (!orderedNamespaces.includes('value')) {
    blocks.push('');
    blocks.push('export interface CnosValueConfig {}');
  }

  if (!orderedNamespaces.includes('secret')) {
    blocks.push('');
    blocks.push('export interface CnosSecretConfig {}');
  }

  return blocks;
}

export function generateCodegenContent(
  manifest: NormalizedManifest,
  sourcePath: string,
  typeModuleImport = './cnos',
): GeneratedCodegenContent {
  const schema = manifest.schema ?? {};
  const hasSchema = Object.keys(schema).length > 0;
  const interfaceBlocks = buildNamespaceInterfaces(schema);
  const typesLines = [
    '// Auto-generated by cnos codegen. Do not edit.',
    `// Source: ${sourcePath}`,
    '',
    ...interfaceBlocks,
    '',
    'import type { CnosRuntime } from "@kitsy/cnos";',
    '',
    'export interface TypedCnosRuntime extends CnosRuntime {',
    '  value<K extends keyof CnosValueConfig>(path: K): CnosValueConfig[K] | undefined;',
    '  secret<K extends keyof CnosSecretConfig>(path: K): CnosSecretConfig[K] | undefined;',
    '  require(key: `value.${keyof CnosValueConfig}`): CnosValueConfig[keyof CnosValueConfig];',
    '  require(key: `secret.${keyof CnosSecretConfig}`): CnosSecretConfig[keyof CnosSecretConfig];',
    '}',
    '',
  ];

  if (!hasSchema) {
    typesLines.push('// Hint: add a schema section to .cnos/cnos.yml for typed key generation.');
    typesLines.push('');
  }

  const runtimeLines = [
    '// Auto-generated by cnos codegen. Do not edit.',
    `// Source: ${sourcePath}`,
    '',
    'import { createCnos as _createCnos, type CnosCreateOptions } from "@kitsy/cnos";',
    `import type { TypedCnosRuntime } from "${typeModuleImport}";`,
    '',
    'export async function createCnos(options: CnosCreateOptions = {}): Promise<TypedCnosRuntime> {',
    '  return (await _createCnos(options)) as TypedCnosRuntime;',
    '}',
    '',
  ];

  return {
    typesContent: typesLines.join('\n'),
    runtimeContent: runtimeLines.join('\n'),
    schemaEntryCount: Object.keys(schema).length,
    hasSchema,
  };
}
